llm_kwargs:
  gpt-4o:
      temperature: 0.1
      top_p: 0.1
      max_tokens: 16384

  gpt-5-nano:
      temperature: 1
      max_completion_tokens: 128000

  ollama_chat/qwen3:4b:

llm_to_use:
  main:
    ollama_chat/qwen3:4b
  summarization:
    gpt-4o
